name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: kaua010/fastapi-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set version
        run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV
      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$VERSION .
          docker push $IMAGE_NAME:$VERSION
      - name: Update Kustomize
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          sed -i "s|newTag:.*|newTag: ${VERSION}|" k8s/overlays/dev/kustomization.yaml
          git add k8s/overlays/dev/kustomization.yaml
          git commit -m "Update image tag to ${VERSION}"
          git push
